services:
- docker

env:
- GCC_VERSION=gcc-5
- GCC_VERSION=gcc-7

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- make build

deploy:
  provider: script
  script: make push
