language: minimal
services:
- docker

env:
- GCC_VERSION=gcc-5
- GCC_VERSION=gcc-7

install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- make build

deploy:
- provider: script
  script: make push-latest
- provider: script
  script: make push-tag VERSION=$TRAVIS_TAG
  on:
    tags: true
