name: Makefile CI

on:
  schedule:
    - cron: '00 01 * * 0'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Docker login
      run: docker login --username jaspnas --password ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build and push
      run: make push-latest
