name: Makefile CI

on:
  schedule:
    - cron: '00 01 * * 0'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure && apt-get install docker.io
      
    - name: Docker login
      run: docker login --username jaspnas --password ${{ secrets.DOCKER_TOKEN }}
      
    - name: Install dependencies
      run: make push-latest
